export enum Properties {
	IDENTIFIER = "identifier",
	FILE_FORMAT = "fileFormat",
	OUTER_DIMENSIONS = "outerDimensionsMM",
	MANUFACTURING_PROCESS = "manufacturingProcess",
	MATERIAL = "material",
	LICENSOR = "licensor",
	LAST_REQUESTED = "lastRequested",
	LAST_SEEN = "lastSeen",
	OKHV = "okhv",
	TEST = "test",
	FILE_URL = "fileURL",
	IMAGE = "image",
	SOURCE = "source",
	RELATED_TSDC = "relatedTsDC",
	EXPORT = "export",
	RELEASE = "release",
	ORGANISATION = "organisation",
	DOCS_READINESS_LEVEL = "documentationReadinessLevel",
	VERSION = "version",
	TECH_READINESS_LEVEL = "technologyReadinessLevel",
	CPC_PATENT_CLASS = "cpcPatentClass",
	TIMESTAMP = "timestamp",
	REPO = "repo",
	FUNCTION = "function",
	PERMALINK = "permaURL",
	ORIGINAL_URL = "originalURL",
	HAS_README = "hasReadme",
	HAS_MANUFACTURING_INSTRUCTIONS = "hasManufacturingInstructions",
	HAS_BOM = "hasBoM",
	HAS_USER_MANUAL = "hasUserManual",
	VERSION_OF = "versionOf",
	HAS_IMAGE = "hasImage",
	CONTRIBUTOR_COUNT = "contributorCount",
	SPDX_LICENSE = "spdxLicense",
	HAS_MANIFEST_FILE = "hasManifestFile",
	HAS_COMPONENT = "hasComponent",
	DOCS_LANGUAGE = "documentationLanguage",
	TYPE = "type",
}

export const LICENSE_SCHEME: any = {
	Weak: [
		"CERN-OHL-W-2.0",
		"CC-BY-4.0",
		"https://spdx.org/licenses/CC-BY-SA-4.1",
	],
	Strong: [
		"CERN-OHL-1.1",
		"CERN-OHL-1.2",
		"CERN-OHL-S-2.0",
		"GPL-1.0-only",
		"GPL-1.0-or-later",
		"GPL-2.0-only",
		"GPL-2.0-or-later",
		"GPL-3.0-only",
		"GPL-3.0-or-later",
	],
	"Non-copyleft": [
		"Apache-1.0",
		"Apache-1.1",
		"Apache-2.0",
		"MIT",
		"MIT-0",
		"CC-BY-1.0",
		"CC-BY-2.0",
		"CC-BY-2.5",
		"CC-BY-2.5-AU",
		"CC-BY-3.0-AT",
		"CC-BY-3.0-DE",
		"CC-BY-3.0-NL",
		"CC-BY-3.0-US ",
		"CC-BY-3.0",
		"CC-BY-4.0",
		"CC-BY-SA-1.0",
		"CC-BY-SA-2.0",
		"CC-BY-SA-2.0-UK",
		"CC-BY-SA-2.1-JP",
		"CC-BY-SA-2.5",
		"CC-BY-SA-3.0",
		"CC-BY-SA-3.0-AT",
		"CC-BY-SA-3.0-DE",
		"CC-BY-SA-4.0",
		"CC0-1.0",
		"CERN-OHL-P-2.0",
	],
};
